const {PGlite}=require('@electric-sql/pglite'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
const db=new PGlite(), owner='11111111-1111-1111-1111-111111111111',manager='22222222-2222-2222-2222-222222222222',student='33333333-3333-3333-3333-333333333333',group='44444444-4444-4444-4444-444444444444';
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;
CREATE TABLE auth.users(id uuid PRIMARY KEY); INSERT INTO auth.users VALUES ('${owner}'),('${manager}');
CREATE TABLE user_profiles(id uuid PRIMARY KEY,role text,is_active boolean); INSERT INTO user_profiles VALUES ('${owner}','owner',true),('${manager}','manager',true);
CREATE TABLE manager_permissions(user_id uuid,permissions jsonb); INSERT INTO manager_permissions VALUES ('${manager}','{"attendance_edit":true}');
CREATE TABLE groups(id uuid PRIMARY KEY,session_price numeric); INSERT INTO groups VALUES ('${group}',15);
CREATE TABLE students(id uuid PRIMARY KEY,group_id uuid,is_active boolean,points_balance numeric,due_amount numeric,due_sessions_count integer); INSERT INTO students VALUES ('${student}','${group}',true,83,0,0);
CREATE TABLE attendance(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),student_id uuid,package_id uuid,package_consumed boolean DEFAULT false,payment_status text,charge_amount numeric,paid_amount numeric,points_change numeric);
CREATE TABLE payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),student_id uuid,amount numeric,payment_method text,paid_at timestamptz,payment_source text,package_id uuid,package_sessions integer);
SELECT set_config('test.uid','${owner}',false);`);
const baseline=fs.readFileSync('supabase/migrations/20260903000100_add_session_packages.sql','utf8');
await db.exec(baseline.slice(baseline.indexOf('CREATE TABLE IF NOT EXISTS public.billing_settings'),baseline.indexOf('CREATE INDEX IF NOT EXISTS student_session_packages_active_idx')));
await db.exec(baseline.slice(baseline.indexOf('CREATE OR REPLACE FUNCTION public.can_manage_session_packages()'),baseline.indexOf('CREATE OR REPLACE FUNCTION public.get_session_package_settings()')));
await db.exec(baseline.slice(baseline.indexOf('CREATE OR REPLACE FUNCTION public.purchase_student_session_package('),baseline.indexOf('GRANT EXECUTE ON FUNCTION public.purchase_student_session_package(uuid, text, uuid)')));
await db.exec(fs.readFileSync('supabase/migrations/20260909000200_add_variable_session_package_size.sql','utf8'));
const migration=fs.readFileSync('supabase/migrations/20260914000100_package_arrears_and_corrections.sql','utf8');await db.exec(migration);await db.exec(migration);
const row=async sql=>(await db.query(sql)).rows[0];
async function rejected(sql,re){let failed=false;try{await db.exec(sql)}catch(e){failed=true;assert.match(e.message,re)}assert.ok(failed,'Expected rejection')}
const buy=(rpc,t=crypto.randomUUID(),n=8)=>`SELECT public.${rpc}('${student}','cash','${t}'${rpc.endsWith('_custom')?','+n:''})`;
await db.exec(`INSERT INTO attendance(student_id,payment_status,charge_amount,paid_amount) VALUES ('${student}','due',15,5)`);
await rejected(buy('purchase_student_session_package_custom'),/سداد/);await rejected(buy('purchase_student_session_package'),/سداد/);
assert.equal((await row('SELECT count(*)::int n FROM payments')).n,0);await db.exec('UPDATE attendance SET paid_amount=15');
await db.exec(buy('purchase_student_session_package_custom',crypto.randomUUID(),70));let r=await row('SELECT * FROM student_session_packages'),id=r.id;
await db.exec(`INSERT INTO attendance(student_id,package_id,package_consumed,payment_status,charge_amount,paid_amount,points_change) VALUES ('${student}','${id}',true,'paid',15,15,10); UPDATE student_session_packages SET sessions_remaining=69 WHERE id='${id}'`);
const correction=(t,r,n)=>`SELECT public.correct_student_session_package('${id}',${t},${r},${n},'Correct entry')`;
await db.exec(`SELECT set_config('test.uid','${manager}',false)`);await rejected(correction(70,69,8),/OWNER_PERMISSION/);await rejected(`SELECT public.get_student_package_purchase_history('${student}')`,/OWNER_PERMISSION/);
await db.exec(`SELECT set_config('test.uid','${owner}',false)`);await rejected(correction(70,70,8),/تغيرت/);await rejected(correction(70,69,0),/INVALID_CORRECTION/);
await db.exec(correction(70,69,8));r=await row(`SELECT * FROM student_session_packages WHERE id='${id}'`);assert.equal(r.sessions_total,8);assert.equal(r.sessions_remaining,7);assert.equal(Number(r.amount_paid),120);
r=await row(`SELECT * FROM payments WHERE package_id='${id}'`);assert.equal(Number(r.amount),120);assert.equal(r.package_sessions,8);
assert.equal(Number((await row('SELECT points_balance FROM students')).points_balance),83);assert.equal(Number((await row('SELECT points_change FROM attendance WHERE package_consumed')).points_change),10);
await rejected(correction(70,69,8),/تغيرت/);await db.exec(correction(8,7,8));assert.equal((await row('SELECT count(*)::int n FROM session_package_corrections')).n,1);
const t=crypto.randomUUID();await db.exec(buy('purchase_student_session_package_custom',t,4));await db.exec(`INSERT INTO attendance(student_id,payment_status,charge_amount,paid_amount) VALUES ('${student}','due',15,0)`);
const before=(await row('SELECT count(*)::int n FROM payments')).n;await db.exec(buy('purchase_student_session_package_custom',t,4));assert.equal((await row('SELECT count(*)::int n FROM payments')).n,before);
await rejected(buy('purchase_student_session_package_custom'),/سداد/);
await db.exec(`UPDATE student_session_packages SET sessions_remaining=6 WHERE id='${id}'`);await rejected(correction(8,6,9),/CONSUMPTION_REQUIRES_REVIEW/);
await db.exec(`UPDATE student_session_packages SET sessions_remaining=7 WHERE id='${id}'; UPDATE payments SET amount=119 WHERE package_id='${id}'`);await rejected(correction(8,7,9),/PAYMENT_REQUIRES_REVIEW/);
await db.exec(`UPDATE payments SET amount=120 WHERE package_id='${id}'`);await db.exec(correction(8,7,1));assert.equal((await row(`SELECT status FROM student_session_packages WHERE id='${id}'`)).status,'depleted');
const priv=await row("SELECT has_table_privilege('authenticated','session_package_corrections','INSERT') AS write, has_function_privilege('anon','correct_student_session_package(uuid,integer,integer,integer,text)','EXECUTE') AS anon_exec");assert.equal(priv.write,false);assert.equal(priv.anon_exec,false);
await db.exec(`UPDATE user_profiles SET is_active=false WHERE id='${owner}'`);await rejected(correction(1,0,2),/OWNER_PERMISSION/);
console.log('PASS: migration repeat; legacy/custom purchases; partial/settled arrears; retry without duplicate payment; correction totals/payment/audit; permissions; stale/invalid correction; unchanged points; consumption/payment mismatch; depleted package; existing consumption with arrears.');await db.close();
})().catch(e=>{console.error(e);process.exit(1)});
